acme_admin:
    resource: "@AcmeAdminBundle/Resources/config/routing.yml"
    prefix:   /

acme_bundle_blog:
    resource: "@AcmeBundleBlogBundle/Controller/"
    type:     annotation
    prefix:   /


